version: '3.9'
services:
  frontend:
    build: 
      context: ./megami-frontend
      args:
        - API_URL=http://localhost:${API_PORT}
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: .
    volumes:
      - uploads:/uploads
    ports:
      - ${API_PORT}:8080
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE}
      SPRING_DATASOURCE_USERNAME: ${USER}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      FRONTEND_URL: http://localhost:${FRONTEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 2s
      retries: 10

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:
  uploads: